### ISSUE TITLE
temporarily remove auto-merging of Dependabot patches

### ISSUE THREAD

**Issue by echappen** [18F/guides#109]
~Per [this decision](https://github.com/18F/guides/pull/107), we will auto-merge Dependabot patches.~

Per the discussion below, we will remove auto-merging temporarily while we figure out the errors around it in #211

**Comment by echappen** [comment]
PR #139 implements this. I will keep watching this to make sure it works as intended.

**Comment by echappen** [comment]
FYI: I'm leaving this issue under "In Review" for now while I monitor Dependabot PRs to check that this is working as intended. Once I get confirmation, I'll move this to Done.

**Comment by echappen** [comment]
I’ve been monitoring how this has been working in practice.

We have a number of (necessary and good) constraints on our git workflow that complicates how auto-merging works:
1. We require all checks to pass before we can merge
2. We require at least 1 approving reviewer before merging
3. We require all PR’s to be up-to-date before merging 

I’ve made a few tweaks to the GH workflow to ensure proper order of operations:
- To accommodate `#1`, I [added a conditional](https://github.com/18F/guides/pull/155) to ensure that all other CI checks pass before this particular workflow is run. 
- To accommodate `#2`, I [added a step](https://github.com/18F/guides/pull/154) in the workflow to automatically approve the PR right before merging it (after confirming that we do want to merge it). 

With these tweaks, I will need to continue monitoring how this works in practice. Since `#3` was enabled recently, I’m still not sure how this will work in combination with the GH workflow. 

The happy path I anticipate is:
1. Dependabot PR’s open in bulk, once per week, each off of the most up-to-date-code
2. If a single patch update is included in that bulk, then once the CI checks pass for that PR, it will be “approved” and merged automatically

Based on behavior I’ve seen so far, I doubt multiple patch updates will be auto-merged at once, because if one patch update gets merged, the other patch update will become out-of-date and blocked from merging. 

We may figure out from all of this that the juice may not be worth the squeeze, and this just creates more work for maintainers, which is what we're trying to reduce.

**Comment by echappen** [comment]
@alexsobledotgov is going to keep monitoring Dependabot PR's for me while I'm away Thanksgiving week. Thanks!

**Comment by jskinne3** [comment]
Today [three](https://github.com/18F/guides/pull/197) [pull](https://github.com/18F/guides/pull/198) [requests](https://github.com/18F/guides/pull/200) failed auto-merge with the error:
```
failed to run git: fatal: not a git repository (or any of the parent directories): .git
```

Hypotheses:
1. An [actions/checkout](https://github.com/actions/checkout) is needed in order to switch to the project directory.
2. Maybe [this issue](https://github.com/actions/checkout/issues/363) currently open in GitHub Actions

**Comment by alexbielen** [comment]
@echappen FYSA https://github.com/18F/guides/issues/211

**Comment by echappen** [comment]
We'll use this issue to handle removing the auto-merging while #211 is being worked on.
