### ISSUE TITLE
Implement "More 18F Guides" button

### ISSUE THREAD

**Issue by christophermather** [18F/guides#130]
### A description of the work

Building off of https://github.com/18F/TLC-crew/issues/507

We'd like to implement a "More 18F Guides" button on individual guides. The link will say "More 18F Guides", sit in the secondary navigation and link to `https://18f.gsa.gov/guides/`

The intent is for this link to be implemented on the **replatformed guides**. 

**Methods:**
![image](https://github.com/18F/guides/assets/97245800/64a726de-08fb-49a2-a70a-11bf6e524dcb)

**Other guides:**
![image](https://github.com/18F/guides/assets/97245800/a4fe7ba4-26b9-470a-aaff-20e29fdbc5f1)

**Mobile:**
![image](https://github.com/18F/guides/assets/97245800/d128426b-70af-4af4-b42f-9af2d7a22b33)

### Point of contact on this issue
Who can we follow-up with if we have questions?

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [ ] No
If yes, tock code:

**Skills needed**
- [ ] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria
- [ ] The replatformed guides template has a "More 18F Guides" button in the secondary navigation

**Comment by igorkorenfeld** [comment]
Completed as part of #113
