### ISSUE TITLE
Ensure top-level page displays in sidebar nav on UX guide

### ISSUE THREAD

**Issue by christophermather** [18F/guides#144]
### A description of the work

This is an issue that affects three sections of the UX guide:
- [Our Approach](https://ux-guide.18f.gov/our-approach/)
- [Research](https://ux-guide.18f.gov/research/)
- [Design](https://ux-guide.18f.gov/design/)

When you navigate to each of these three sections, the top-level page does not appear in the sidebar nav.

For instance, navigating to [Our Approach](https://ux-guide.18f.gov/our-approach/), the first item in the sidebar nav is "Values and principles". In order to follow design conventions in other guides, the first item in the sidebar nav should be "Our Approach".

![image](https://github.com/18F/guides/assets/97245800/6932ad8a-79b2-4aac-a2ce-cace43301e2e)

Likewise, the first item in the sidebar nav under [Research](https://ux-guide.18f.gov/research/) should be "Research" and the first sidebar item under [Design](https://ux-guide.18f.gov/design/) should be "Design".

If you're new to Guides work, read this! [New teammate info](https://docs.google.com/document/d/1iBmKToTK7js65aOsljXirK0yLh--QZ_h6ugXtvqbuRg/edit#heading=h.bsas7w744wxm)

### Point of contact on this issue
Who can we follow-up with if we have questions?

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [ ] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [x] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [ ] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] This sidebar fix is applied to all three sections mentioned: [Our Approach](https://ux-guide.18f.gov/our-approach/), [Research](https://ux-guide.18f.gov/research/) and [Design](https://ux-guide.18f.gov/design/)

ex: As an 18F staff member who is going on parental leave, I can navigate to my
latest Tock reporting period and choose billing line #1810 by filtering by
number or "extended OOO"

**Comment by adunkman** [comment]
I have so ensured.
