### ISSUE TITLE
Develop estimate for Methods replatforming work

### ISSUE THREAD

**Issue by christophermather** [18F/guides#149]
### A description of the work

As discussed, we are evaluating the replatforming of [Methods](https://methods.18f.gov/) pages separately from the other Guides due to their dissimilarity. 

Right now, we lack an understanding of how complex the replatforming effort for these pages will be.

We need to do a little digging to develop an estimate for how much effort it will take to replatform. This estimate can be rough: we want medium-high confidence but only need low fidelity. Meaning: 

- **This is way easier than we thought.** Compared to the Agile guide, it will take less effort..
- **This is about as complex as we thought.** It's at least as much more work as the Agile guide.
- **This is far more complex than we expected.** It's hard to estimate how much work it will take to complete.

### Point of contact on this issue

@christophermather

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [X] Yes
- [ ] No

### Acceptance Criteria

- [ ] We have a rough understanding (and estimate) of level of effort to replatform the Methods pages

**Comment by igorkorenfeld** [comment]
After doing some research on the existing Methods repository it does seem like replatforming this site will indeed take **more effort** than the other guides. 

I have captured [some notes](https://docs.google.com/document/d/1FREjKBhwDTdbhaWeN6xFjfIk4QnRhU9FtF1i7qT11BY/edit?usp=sharing) which outline in a bit more detail the additional work required for replatforming Methods. It lays out the major segments of works and a suggested sequence.

**Comment by igorkorenfeld** [comment]
@juliaklindpaintner and @alexsobledotgov leaving this one in the In Review column so other folks can comment. 

Possible follow on work here is for the guides leads to make a decision on if the sequence makes sense, and to create tickets that correspond with the work break down.

**Comment by christophermather** [comment]
Created new issue to generate new issues from Igor's rec's: #206
