### ISSUE TITLE
[Bug]: Some old guide url paths won't map to their new paths

### ISSUE THREAD

**Issue by echappen** [18F/guides#244]
### Contact Details

`@Eleni Chappen` on slack

## The problem

Our [URL redirections](https://github.com/cloud-gov/pages-redirects/blob/main/templates/_federalist-redirects.njk#L557) on Cloud.gov work like this: “For any old guide page, take the old URL path and stick it to the end of the new guide domain to get to the new page.”

For example, the code linked above says that:
https://content-guide.18f.gov/abbreviations-and-acronyms/
_should_ redirect to:
https://guides.18f.gov/content-guide/abbreviations-and-acronyms/
because they have the same path of `/abbreviations-and-acronyms/`.

For the majority of our new URL’s, this code works. But two of the guides—content and engineering—have a good number of old URL’s that won’t map 1:1 like this. (27 pages for content; 36 for engineering.) 

This is due to some new pages being nested in additional directories in the new repo. 

For example, this old URL:
https://content-guide.18f.gov/abbreviations-and-acronyms/
now lives at this new URL that has an additional sub-directory of `our-style`:
https://guides.18f.gov/content-guide/our-style/abbreviations-and-acronyms/

This results in 404’s for redirects of old URL’s with paths that do not directly map to new URL paths.

## How to fix

Our solution depends on whether we want to keep the new url structures (i.e. keep the additional nesting) as is. 

If we do, then we will need to write 301 redirect logic for each of the 60+ non-mapping URL’s on cloud.gov’s [site-redirects](https://github.com/cloud-gov/pages-redirects) repo.

If we don’t, then we can adjust the new url’s in our own repo by changing the `permalink` for each non-mapping page to map to its old path.

#### pros:
- We can keep the current directory structures as is on our repo

#### cons:
- More custom code to implement on someone else’s repo
- We do not fully control when or how these changes are implemented
- Will need to go back to cloud.gov if we want to change these down the road

#### Pros:
- We control the changes; we can change them anytime
- Less code to manage on another org's repo
- New URL paths stay the same as old URL paths

#### cons:
- Some live URLs for the content guide will change. We will need to reindex the content guide pages for search engines, as those pages are already live (engineering is not live yet). We will do this by adding a robots.txt to the site once the URL changes have been made.

### Version

1.0.2 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliaklindpaintner** [comment]
@echappen Can you confirm this is done?

**Comment by echappen** [comment]
This was completed in #260, #261, and #263
