### ISSUE TITLE
Decide what to do w/ old Guides repos post-migration

### ISSUE THREAD

**Issue by christophermather** [18F/guides#257]
### A description of the work

Background: all guides are migrating to a consolidated repo. We need to decide what to do with the old guides repos once all migrations are complete.

Some ideas:

- Set repo to read-only
- Add text about where the guide now lives
- Add text about where to submit new issues

### Point of contact on this issue

@christophermather

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria

- [ ] We agree on the changes we should make to the guides repos post-migration
- [ ] Changes are implemented on all guides repos

**Comment by adunkman** [comment]
I’d like to move forward with at least: 

- Adding text to the README that says where the guide now lives
- Archiving the repo

Feel free to consider if there are additional tasks that should be done as well.

**Comment by christophermather** [comment]
After reviewing all

**Comment by christophermather** [comment]
@juliaklindpaintner and/or @cantsin : can we assign someone with appropriate admin privileges to archive the following old guides repos?
[Brand](https://github.com/18F/brand)
[De-risking](https://github.com/18F/derisking-gov-tech)
[Engineering](https://github.com/18F/development-guide)

The archive settings should match other old guides repos (like [accessibility](https://github.com/18F/accessibility), for instance).

Archiving those repos should satisfy the criteria for this ticket (at which point it can be closed).

**Comment by juliaklindpaintner** [comment]
Thanks @christophermather — yes we can do that. @adunkman do you already have permissions? If so, could you do the honors?

**Comment by adunkman** [comment]
I don’t have the needed permissions, but we can ask in #admins-github!

**Comment by juliaklindpaintner** [comment]
Cool, I'll take it there! Thanks, @adunkman.

**Comment by juliaklindpaintner** [comment]
Just archived brand, de-risking, and engineering repos!
