### ISSUE TITLE
Drop yellow banner at top of Guides

### ISSUE THREAD

**Issue by christophermather** [18F/guides#266]
### A description of the work

With the hard release of the final batch of Guides happening this Thursday, we should drop the yellow banner at the top of the replatformed guides.

<img width="988" alt="image" src="https://github.com/18F/guides/assets/97245800/271e3b15-f6dd-4c10-b032-cbb6624e5520">

Background: my guess is that this banner was put in place for the interval between soft and hard release in case anyone found themselves on a replatformed guide before our redirects were in place.

Once we complete the hard release of the final batch, I think this banner will be obsolete.

Let's remove it!

### Point of contact on this issue

@christophermather

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria

- [ ] The yellow banner is gone from all/any replatformed Guides

**Comment by adunkman** [comment]
Edited to remove the question — yes, let’s remove these banners as described.
