### ISSUE TITLE
Recreate interview checklist for methods

### ISSUE THREAD

**Issue by jduss4** [18F/guides#294]
### A description of the work

On the current methods website, there is an [interview checklist](https://methods.18f.gov/interview-checklist/) with actual checkboxes.  However, 11ty doesn't render these by default, so they come out looking like `- [ ]`

Off the top of my head I can think of a couple options:

1. Use HTML for the checkboxes
2. [Extend the markdown parser](https://github.com/11ty/eleventy/issues/3107)
3. Change the checkboxes to bullet points (requires design input)

### Point of contact on this issue

jduss4

### Skills Needed

- [ ] Any Human
- [X] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [X] Yes
- [ ] No

### How much time do you anticipate this work taking?

4 hours

### Acceptance Criteria

The new methods guide page for the interview checklist either has checkboxes or an approved alternative

**Comment by echappen** [comment]
Noting that I tried installing the [markdownIt extension package](https://github.com/linsir/markdown-it-task-checkbox) that [issue](https://github.com/11ty/eleventy/issues/3107) links to, but its dependencies require conflicting Node versions, so I was hesitant to use it.

**Comment by echappen** [comment]
I also noticed that the UX guide has a [very similar interview checklist](https://guides.18f.gov/ux-guide/interview-checklist/) with un-styled markdown checkboxes.

**Comment by echappen** [comment]
Given that the released ux guide has the same issue, I'm going to consider this out-of-scope for the methods migration epic: https://github.com/18F/guides/issues/224

**Comment by igorkorenfeld** [comment]
Came across this and thought I'd note that the derisking guide has some [checklists](https://guides.18f.gov/derisking/state-field-guide/budgeting-tech/#checklist), and the way I resolved it there was with styling the bulleted list by adding a [class](https://github.com/18F/guides/blob/d03045977bc0e8e7085f98dbb791312ccfc680b7/content/derisking/state-field-guide/3-budgeting-tech.md?plain=1#L63) to the preceding text using the `markdown-it-attrs` plugin

**Comment by echappen** [comment]
Here's a PR that demonstrates what Igor's suggestion looks like: https://github.com/18F/guides/pull/436
