### ISSUE TITLE
🟢 Describe rationale for participant sample size in our work

### ISSUE THREAD

**Issue by bpdesigns** [18F/guides#307]
**Is your feature request related to a problem? Please describe.**
Project partners who are not used to qualitative research question the number of participants we include in research phases as not significant because we do not talk to a large number of people to inform our research insights. 

**Describe the change you'd like to see**
Add text to the "Plan" phase of user research that give clarity on the number of people needed to learn from in different user research practices.

**Additional context**
[scratchpad](https://docs.google.com/document/d/1ZeAdT80Nkuh40dYjXBhoMT-Lj5e0Ez8K--foVcKS7S0/edit) of possible content to include

**Add reviewers** 
TBD

**Comment by cantsin** [comment]
Need clarification on next steps

**Comment by bpdesigns** [comment]
This content is better as a resource than as main page content. I'll wrap this into issue [506](https://github.com/18F/guides/issues/506) related to the UX guide resources.
