### ISSUE TITLE
Roadmap Page Documents -- Review Public Access

### ISSUE THREAD

**Issue by caseywatts** [18F/guides#311]
Could someone review the documents linked to from this page to see if they could be shared publicly? It would help me out a lot to reference these 18F documents about roadmaps! :)
https://product-guide.18f.gov/define/roadmap/

(I'm filing an issue here as specified in this PR:
https://github.com/18F/product-guide/pull/163/files )

Related to 18F/product-guide#163

**Comment by allisonnorman** [comment]
As we review outstanding issues, I see a couple of requests related to opening up our resources externally. I'm going to close this issue but have linked it in the one we'll keep open and will prioritize along with other guide work: #252.
