### ISSUE TITLE
🟢 Remove link

### ISSUE THREAD

**Issue by vickimcfadden** [18F/guides#312]
This page (https://derisking-guide.18f.gov/federal-field-guide/planning/#leadership-should-set-direction-and-empower-teams) on the "oversight processes" link directs folks to a private / locked google document. Recommend seeing if there is anything we should pull out of this doc and put accessible in a PDF or simply remove the link. 

Private google doc: https://docs.google.com/document/d/1h3UBJk2PhggKu4LgCZQXCNvtXnFY3q6hv34bs-nysvo/edit#heading=h.vkxvfzdbntky

Tasks
- [x] Check with @adunkman whether he wants to make an accessible PDF with any of the info in the doc
- [x] Remove the link or replace with accessible PDF

**Comment by jdamis4XD** [comment]
@adunkman Need confirmation from you on a few things.

1. Can you please confirm if you want to make the `[De-risking Government Technology](https://docs.google.com/document/d/1h3UBJk2PhggKu4LgCZQXCNvtXnFY3q6hv34bs-nysvo/edit?usp=sharing)` document that is linked from [De-risking Guide](https://docs.google.com/document/d/1h3UBJk2PhggKu4LgCZQXCNvtXnFY3q6hv34bs-nysvo/edit?usp=sharing) accessible via PDF.  The document is currently locked in a google doc.

2.  The De-risking Government Technology has the [Planning ]([url](https://docs.google.com/document/d/1VOeXRAHDRy6QrKmrcgRlxp-KsrKT2uimQB63p0dR3GQ/edit?usp=sharing))and the [Deciding](https://docs.google.com/document/d/1xkRQtC9VcxjG3DQxauHz3oAIT3uF4k-zO2jxRlfS9Co/edit?usp=sharing) sections were edited and received final approval in Aug 2020.  Are we okay to proceed with publishing theses sections if the answer to the first question, is yes?

**Comment by adunkman** [comment]
Thanks for the question! There are updates to this guide to cover vendor management and oversight more in-depth currently underway in another workstream, and the spirit of what is linked is already published. We should remove the link without publishing the attached document.

**Comment by jdamis4XD** [comment]
Removed the link to the PDF and submitted the PR for approval.
