### ISSUE TITLE
🟢 Federal guide PDF has wrong intro sentence for Deciding What to Buy

### ISSUE THREAD

**Issue by jstrothman** [18F/guides#315]
The pdf & html versions of the Federal Field Guide have different intro sections for the `Deciding what to buy` chapter.

The **html version seems correct:**
* 2 Planning: "The following sections identify challenges and strategies to mitigate risk while planning custom technology projects in government."
* 3 Deciding what to buy: "The following sections identify challenges and strategies to mitigate risk during the research and solicitation phase of custom technology projects in government."

The **PDF version repeats section 2's intro line in section 3**:
* 2 Planning: "The following sections identify challenges and strategies to mitigate risk during the planning phase of custom technology projects in government."
* 3 Deciding what to buy: "The following sections identify challenges and strategies to mitigate risk during the planning phase of custom technology projects in government."

**Acceptance criteria**
- [x] Federal Field Guide pdf has the correct text
- [x] Derisking guide links to corrected Federal Field Guide for download

**Comment by christophermather** [comment]
Confirmed that this remains true. For help tracking down, see the [printable PDF](https://guides.18f.gov/assets/derisking/dist/federal-field-guide.pdf) here.

Page 20: Planning section intro
<img width="452" alt="image" src="https://github.com/18F/guides/assets/97245800/a88527f8-eed5-4cf9-8032-0d809a3ba0a5">

Page 60: Deciding What to Buy section intro
<img width="450" alt="image" src="https://github.com/18F/guides/assets/97245800/2f4cfad7-7062-4273-80f5-397d0be382cf">

Text is the same in both intros on PDF, which is wrong. Text is different on the website ([Planning](https://guides.18f.gov/derisking/federal-field-guide/deciding-what-to-buy/) vs. [Deciding](https://guides.18f.gov/derisking/federal-field-guide/planning/)), which is right.

**Comment by jdamis4XD** [comment]
I found the editable PDF and saved the original and updated file in a new [TLC folder](https://drive.google.com/drive/folders/12iWM7FYFlBUPRq1XtO577IEnB0yeeEpe?usp=drive_link).

**Comment by jdamis4XD** [comment]
Submitted the PR for review and approval.

**Comment by jdamis4XD** [comment]
Submitted another PR as I needed to update the Federal Field Guide page which linked to the document from a different /dist/federal-field-guide.pdf path.
