### ISSUE TITLE
🔴 Create a set of secondary colors for use in data visualizations

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/guides#317]
We need a set of colors that can be used for different types of data visualizations. These colors would be used in charts on internal and possibly external reports. 

The current set of brand colors is limited, and does not work well for divergent color schemes.

**Comment by igorkorenfeld** [comment]
I have a set I've worked up and will test out

**Comment by bpdesigns** [comment]
@igorkorenfeld is this something that a member of TLC can help test out?

**Comment by igorkorenfeld** [comment]
Closing, will share when have ready for testing.
