### ISSUE TITLE
🟡 Consider guidance on making better graphs in presentations

### ISSUE THREAD

**Issue by cmajel** [18F/guides#318]
An idea from @jstrothman that came up in conversation. Similar to our "[how to design a better deck](https://docs.google.com/presentation/d/1WMbN1feG1bMhaFx5YbXoYUTE7xgZdMewMaQBZeL3YmA/edit?usp=drive_web&ouid=109014321948983622633)" presentation, we could provide similar guidance for how to make better graphs and data visualizations. Ideas included:

* Providing guidance on which ways to compare
* Extended color palette suggestions using USWDS for use in charts and graphs 
* General data visualization guidance

@jstrothman  mentioned @artfulaction as someone who may be good to pair with on this.

**Comment by igorkorenfeld** [comment]
🟡   Unsure if this is still a need. Can either explore or close. Overlaps somewhat with #317

**Comment by bpdesigns** [comment]
Closing as a non priority enhancement
