### ISSUE TITLE
🔴 Consider simplifying the IA

### ISSUE THREAD

**Issue by cmajel** [18F/guides#319]
From our 12/8 sync. 

We talked a bit about simplifying the IA on the new site layout. One idea was creating an "assets" section or dropdown that holds logo, typography, color, icons, templates, and desktop art, with a sidenav to navigate within that section. 

Current nav on new layout:
![Screen Shot 2020-12-08 at 2 24 25 PM](https://user-images.githubusercontent.com/2374206/101531341-1ca33100-3961-11eb-93a5-098a2271a74e.png)

**Comment by igorkorenfeld** [comment]
🔴 Currently structure seems to be working for us, but open to revisiting in the future
