### ISSUE TITLE
🟡 Document Credential management practices

### ISSUE THREAD

**Issue by rahearn** [18F/guides#322]
https://engineering.18f.gov/security/ should have a section on credential management in all phases of a project.

I'll volunteer to get a first draft started, welcome anyone else to pitch in as well.

**Comment by bpdesigns** [comment]
@cantsin could you assess if this issue is still relevant? It doesn't look like a management process was added to this guide

**Comment by cantsin** [comment]
Still relevant. We do need something about credential management in the guides. Let me think about this a bit more. Maybe one of the new principal engineers can pick this up.

**Comment by rahearn** [comment]
@jduss4 and I started noodling on this a little bit but both of us had to put it down due to project work. I'd be happy to continue participating in shaping it / contributing content

**Comment by jduss4** [comment]
Same, we have quite a bit written up, just needs to be finished up and weighed in on!

**Comment by bpdesigns** [comment]
Great! Thanks @jduss4 @rahearn
