### ISSUE TITLE
Add checkbox styling to replatformed Guides and Methods

### ISSUE THREAD

**Issue by christophermather** [18F/guides#341]
### A description of the work
Add Markdown checkbox styling to replatformed Guides and Methods.

Currently, migrated pages show `- [ ]` instead of a checkbox. In addition, the old guides and methods pages had awkward checkbox styling with the bullet.

### Point of contact on this issue
@AnitaYCheng 

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [x] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### How much time do you anticipate this work taking?

1-2 days for an engineer.

_No response_

### Acceptance Criteria

- [ ] Markdown files in Guides and Methods containing `- [ ]` resolve into a recognizable checkbox.

**Comment by echappen** [comment]
related to #294 where some notes on implementation have been documented.

**Comment by jduss4** [comment]
@echappen I suspect this may be done after your work on https://github.com/18F/guides/pull/436 ?

**Comment by echappen** [comment]
Maybe? I just did it for Methods in $436 so I'll check the rest of the guides.

**Comment by echappen** [comment]
@jduss4 Here's a fix for the rest of the checkboxes throughout the guides: https://github.com/18F/guides/pull/438

**Comment by jduss4** [comment]
Good work, I didn't realize we had so many checklists!
