### ISSUE TITLE
Archive old guide repositories (post-migration)

### ISSUE THREAD

**Issue by christophermather** [18F/guides#342]
### A description of the work
Archive the Github repository for each of the legacy guides.

#### Guides and repo links ####
Here are the various guide repository links:
- [accessibility](https://github.com/18F/accessibility)
- [agile](https://github.com/18F/agile)
- [brand](https://github.com/18F/brand)
- [content-guide](https://github.com/18F/content-guide)
- [derisking](https://github.com/18F/derisking-gov-tech)
- [eng-hiring](https://github.com/18F/eng-hiring)
- [engineering](https://github.com/18F/development-guide)
- [product](https://github.com/18F/product)
- [ux-guide](https://github.com/18F/ux-guide)

### Point of contact on this issue

@eric-gade

### Reproduction steps (if necessary)

- Ensure you have the correct permissions on the given guide repository
- Archive the repository on Github by going into the repo's specific settings

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### How much time do you anticipate this work taking?

Assuming the implementer has the correct permissions, this should take about an hour

### Acceptance Criteria

- [ ] Each guide github repository is archived and can no longer be written to

**Comment by echappen** [comment]
done
