### ISSUE TITLE
Add non-endorsement copy to the Guides website

### ISSUE THREAD

**Issue by christophermather** [18F/guides#347]
### A description of the work

Per https://github.com/18F/TLC-crew/issues/341, we need to add non-endorsement copy to our Guides website. 

Background: we've already added appropriate icons to external, non-federal links. Now, we need language that clarifies our non-endorsement policy.

Other sites seem to address this by having a specific page that articulates the non-endorsement policy (sometimes alongside other website policies). This includes the 18F website. Examples:
- [18F linking policy](https://18f.gsa.gov/linking-policy/)
- [USWDS website policies](https://designsystem.digital.gov/about/website-policies-notices/) (scroll to "Linking Policy")
- [USA.gov linking policy](https://www.usa.gov/linking-policy)

Suggestion: 
- We model ourselves after these websites and create a linking policy page. 
- We could/should use similar or the same language as the [18F website policy](https://18f.gsa.gov/linking-policy/)
- If we adjust the language, we should determine if the 18F website language needs an update, as well
- We could link to the linking policy in the Guides sub-footer (see below)
<img width="901" alt="image" src="https://github.com/18F/guides/assets/97245800/d69c7e68-6357-44a9-9855-574f27caac37">

### Point of contact on this issue

@christophermather

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria

- [ ] The 18F Guides have a "Linking Policy" page with approved language
- [ ] The "Linking Policy" page is accessible from any 18F Guides page

**Comment by peterrowland** [comment]
One complication is that there is no landing page within the guides repo or place for common content within the guides repo. 

It may be more practical to simply add a link to the existing 18F linking policy, which should equally apply to the guides anyway.

**Comment by christophermather** [comment]
This makes sense to me, @peterrowland. 

What about something like the below?

![Image](https://github.com/18F/guides/assets/97245800/a6801036-aba0-442b-844c-24807e2b81dd)

Add text that says "Learn more about our [linking policy](https://18f.gsa.gov/linking-policy/)" (where "linking policy" links to `https://18f.gsa.gov/linking-policy/`)

Pinging @adunkman for gut check. Summary:

- In order to be compliant w/ non-endorsement regulations, we need to include specific language on our websites where we link to non-fed resources
- The Guides (obviously) have a lot of links that point to non-fed resources
- Other sites (including 18F) address this need by including a "Linking policy" page that they link to in the footer
- We discussed creating our own "Linking policy" page specifically for Guides
- Peter is suggesting that we simply link to the 18F site "Linking policy"instead

Let us know what you think.

**Comment by adunkman** [comment]
Yes, please proceed with the plan to link to 18F’s Linking policy — we have similar challenges with our blog, and it’s best to keep one policy rather than duplicate. Thanks for the run down! 👍
