### ISSUE TITLE
Conduct Accessibility review of methods

### ISSUE THREAD

**Issue by echappen** [18F/guides#357]
### A description of the work

After https://github.com/18F/guides/issues/236 is done, let's do a manual accessibility review. Since the methods site is so visually different from the other sites and required more custom work on layouts, I think it's worth doing a full a11y review before launching the new site. 

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

**Comment by echappen** [comment]
Here's a build we can use for review: https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/eoc/269/methods/

**Comment by echappen** [comment]
@jasnakai We had success creating labeled issues for design review. If any issues come out of review, could you create them as new issues in GH and label them as `a11y`? That'll make them easier to find and address.

**Comment by jasnakai** [comment]
Awesome! You got it.

**Comment by jasnakai** [comment]
Accessibility audit is complete. The only issue found was the multiple h1's per view documented here: #447 .
