### ISSUE TITLE
[Bug]: Card titles missing underline

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#361]
### Description and Screenshots

The card titles on the old site are underlined to indicate they're links. We should bring this back into the new site.

New site:
![image](https://github.com/18F/guides/assets/2846578/3e8d8095-967d-48b4-93c0-3524d05055a4)
- No underline, no hover effect

Old site:
![image](https://github.com/18F/guides/assets/2846578/fd90c6d0-7537-45b1-9b4a-a87f90c2a2f4)
- Underline, which disappears on hover to show change

### Link to where you found the issue

https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/eoc/fix-button-link-methods/methods/decide/

**Comment by juliaklindpaintner** [comment]
Additional nuance here: The underline seems only to appear on the old Methods site when looking at a page of all the cards in a section. When you look at an individual card page, it displays without an underline, but with a launch icon: 

Old site "All Discover" page: 
![Screenshot 2023-12-21 at 4 55 13 PM](https://github.com/18F/guides/assets/42982184/f91d509a-2737-4392-b5cd-d7252488f46d)

Old site individual card within Discover page: 
![Screenshot 2023-12-21 at 4 58 23 PM](https://github.com/18F/guides/assets/42982184/0a305c08-1ceb-42db-9245-f84d177a7409)

New site looks like this in both instances: 
![Screenshot 2023-12-21 at 4 55 17 PM](https://github.com/18F/guides/assets/42982184/f54639aa-1d40-485f-a688-47366402f249)

**Comment by melchoyce** [comment]
Okay I have to admit the external icon in "Old site individual card within Discover page:" is weird and feels like a bug.
