### ISSUE TITLE
[Bug]: External resources missing external icons

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#367]
### Description and Screenshots

The new site should append an external icon to any links going outside of the Methods site (or maybe the whole 18F site? Was there an issue for that?)

New site:
![image](https://github.com/18F/guides/assets/2846578/82ec4547-3a1b-4a8c-ab13-7e14b4022a86)

Old site:
![image](https://github.com/18F/guides/assets/2846578/1a20231c-9efc-4522-8d0c-77ea89594d07)

Note, the icon _is_ appearing on [this card](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/eoc/fix-button-link-methods/methods/decide/comparative-analysis/) and [this card](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/eoc/fix-button-link-methods/methods/decide/design-principles/) so I'm not sure what's going on.

### Link to where you found the issue

https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/eoc/fix-button-link-methods/methods/decide/content-audit/, https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/eoc/fix-button-link-methods/methods/decide/journey-mapping/

**Comment by juliaklindpaintner** [comment]
Weirdly, I came across one resource that did show that icon and wanted to note it here in case it can be leveraged for a solution: 
![Screenshot 2023-12-22 at 9 55 19 AM](https://github.com/18F/guides/assets/42982184/46279eda-6155-48b3-8fac-74587bf2afdf)
![Screenshot 2023-12-22 at 9 59 27 AM](https://github.com/18F/guides/assets/42982184/4425c39b-937a-421a-bd75-f6a7654fe19e)

**Comment by echappen** [comment]
Related to https://github.com/18F/guides/issues/274
