### ISSUE TITLE
[Request]: Update punctuation in "Service blueprint" card

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#371]
### A description of the work

There is a mix of punctuation going on in the Service blueprint card. For example, two of these bullet points have a period, but the rest don't:

![image](https://github.com/18F/guides/assets/2846578/dab479e5-2b04-4679-a808-5c80584ba37d)

And, this sentence is missing a period:

![image](https://github.com/18F/guides/assets/2846578/7fd92be8-0ab5-4c1c-9d9c-9f0f5ffffe65)

### Point of contact on this issue

Content guild maybe?

### Skills Needed

- [ ] Any Human
- [ ] Design
- [X] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

1 hr

### Acceptance Criteria

The punctuation is consistent and follows 18F's content guidelines.

**Comment by bpdesigns** [comment]
@c-collins Feel free to pick this one up!
