### ISSUE TITLE
[Bug]: Some external link icons missing on About page

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/guides#383]
### Description and Screenshots

External link ("launch") icons are missing on some, but not all, of the external resources on the About page. I took screenshots where they are missing. 

Old site: 
![Screenshot 2023-12-22 at 10 10 45 AM](https://github.com/18F/guides/assets/42982184/983d6a30-52ed-47c8-9af6-c7eb89435134)
New site is missing the icons after digital.gov and "18F's User Experience Design Guide" (perhaps the latter is now an internal link and therefore shouldn't have it):
![Screenshot 2023-12-22 at 10 10 40 AM](https://github.com/18F/guides/assets/42982184/52a26b04-0875-4177-b18a-be4a8d8a8eef)

Old site: 
![Screenshot 2023-12-22 at 10 14 26 AM](https://github.com/18F/guides/assets/42982184/f2c30af2-8326-4b6e-87b1-dedd28a42230)
New site is missing icon after PRA:
![Screenshot 2023-12-22 at 10 11 59 AM](https://github.com/18F/guides/assets/42982184/fbe0cba2-cbac-4f9c-9b02-fe3a77608332)

### Link to where you found the issue

https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/eoc/fix-button-link-methods/methods/about/

**Comment by echappen** [comment]
This may be related to https://github.com/18F/guides/issues/274
