### ISSUE TITLE
[Bug]: "See all [Phase] cards" button links back to homepage

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/guides#390]
### Description and Screenshots

Throughout all sections of the website, when looking at an individual card, there is a "See all [Phase] cards" button that should link to the page that shows all cards in that section. On the new site, those buttons link back to the homepage. 

Example: 
On the old site, from Cognitive Walkthrough page, clicking the button links to all Discover cards page.
![Screenshot 2023-12-22 at 11 23 20 AM](https://github.com/18F/guides/assets/42982184/263b8dbd-0c41-4b2e-8c9d-0376d1ba0497)
![Screenshot 2023-12-22 at 11 23 25 AM (2)](https://github.com/18F/guides/assets/42982184/b940705d-8a4c-41cd-a0e4-3dd07ae017cc)

On the new site, from Cognitive Walkthrough page, clicking the button links back to the main page.
![Screenshot 2023-12-22 at 11 24 08 AM](https://github.com/18F/guides/assets/42982184/047d09fe-1615-43e7-a8ad-323ae934131d)
![Screenshot 2023-12-22 at 11 24 52 AM](https://github.com/18F/guides/assets/42982184/0de65341-5ecf-46ca-8d06-736c4ccd3d44)

### Link to where you found the issue

https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/eoc/235/methods/discover/cognitive-walkthrough/

**Comment by echappen** [comment]
Fixed in https://github.com/18F/guides/pull/355
