### ISSUE TITLE
Add a problem framing card

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/guides#396]
Based on research conducted in 10x Users First project, @lalitha-jonnalagadda and @annahsgraves provided the following:

Problem:
Users lack information they need to effectively conduct problem framing prior to digging into research
As a part of our closing recommendations for phase 2, would suggest making the following updates/changes to help solve the issues outlined above.

Suggested solution: 
Add a problem framing card

**Comment by bpdesigns** [comment]
Closing this as duplicative of Product Outcome Statement in Decide [#398](https://github.com/18F/guides/issues/398)
