### ISSUE TITLE
[NEW METHOD]: Content highlighter testing

### ISSUE THREAD

**Issue by michelle-rago** [18F/guides#513]
### A description of the work

Create a method card that describes how to use a highlighting method to test content.

### Point of contact on this issue

Michelle Rago

### Skills Needed

- [ ] Any Human
- [ ] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### Acceptance Criteria

Review and publish method

### Tasks

- [x] Review - [content highlighter testing](https://docs.google.com/document/d/1FSdVyx7KZPXdzaQHgCIVgBUH2-yZWCbjjP1mp2vxnXs/edit#heading=h.dujq2ioimu08)
- [x] Share with @michelle-rago for feedback
- [x] Publish

**Comment by michelle-rago** [comment]
@michelle-rago will get this content ready for peer review and then hand it off to the next TLC team

**Comment by michelle-rago** [comment]
Added a highlighting test example from @amandacostello. @lauranash18f What do you think of [this method card on content highlighting](https://docs.google.com/document/d/1FSdVyx7KZPXdzaQHgCIVgBUH2-yZWCbjjP1mp2vxnXs/edit) (that we discussed so long ago)?

**Comment by lauranash18f** [comment]
I LOVE IT! I have one tiny note on a sentence that stuck out to me, but this otherwise looks excellent. Thrilled this exists.

**Comment by bpdesigns** [comment]
@lauranash18f can you add your note on the sentence that you reference above to the draft doc? Or let me know if we should publish as is?

**Comment by bpdesigns** [comment]
Adding this ticket back to prioritized and updating the task list to move this forward

**Comment by qmanderson1** [comment]
Unassigned this for someone to pick up next sprint - I was not able to get to this during this sprint due to being out on sick leave and various other blockers.

**Comment by michelle-rago** [comment]
I have time to publish this. Any objections to moving this forward? @lauranash18f @amandacostello

**Comment by lauranash18f** [comment]
None here, I thought it was up already! Go for it!
