### ISSUE TITLE
[Request]: Remove "Research alignment workshop" from UX Guide resources

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/guides#524]
### A description of the work

Based on https://github.com/18F/guides/issues/291, the UX Guide resources were assessed. The Research alignment workshop was flagged to be further evaluated for inclusion. At a meeting of the Design Chapter, a quick review of the resource revealed that it was a) not in use and b) taken from (and credited to) [The Working Group's user research playbook](https://twg-x-uxr.gitbook.io/plays/research-alignment-workshop). Given those two factors, the recommendation was made to remove it from the guide and develop something that could be a more generalized template for an alignment workshop.

### Point of contact on this issue

Julia Lindpaintner

### Skills Needed

- [X] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

1 hour

### Acceptance Criteria

- [x] The Research alignment workshop page is removed from the UX guide.
- [x] Any internal links to the Research alignment workshop page are removed, such as on the [Resources](https://guides.18f.gov/ux-guide/resources/) page and [Research > Plan](https://guides.18f.gov/ux-guide/research/plan/) page.

**Comment by jasnakai** [comment]
Closed with PR: #552 .
