### ISSUE TITLE
Decide to remove links to external PDFs that trigger a 403 error

### ISSUE THREAD

**Issue by jasnakai** [18F/guides#559]
Sub-ticket of https://github.com/18F/guides/pull/558. This issue is to make a decision on removing the links to external PDFs that are hosted by the standishgroup.com whose security certificate is expired resulting in a 403 error.

The links are in the footnotes section of the Deriskng guide.

- Page: https://guides.18f.gov/derisking/state-field-guide/budgeting-tech/	
  - Link text: "software projects that cost more than $10 million succeed only 8% of the time"
    - URL: https://www.standishgroup.com/sample_research_files/CHAOSReport2014.pdf
  - Link text: "software projects’ outcomes get worse as more money is spent"
    - URL: https://www.standishgroup.com/sample_research_files/CHAOSReport2014.pdf
- Page: https://guides.18f.gov/derisking/federal-field-guide/	
  - Link text: "Haze"
    - URL: https://www.standishgroup.com/sample_research_files/Haze4.pdf
- Page: https://guides.18f.gov/derisking/state-field-guide/
  - Link text: "Haze"
    - URL: https://www.standishgroup.com/sample_research_files/Haze4.pdf

**Comment by bpdesigns** [comment]
waiting for a review from the derisking guide code owner

**Comment by jasnakai** [comment]
Hello @adunkman. As the code owner, what action would you like for us to take on this ticket? The links to the external PDFs are encountering an error of "Access denied due to bad server certificate". Should we remove the footnotes entirely, just remove the links, or something else? Thank you!
![Screenshot 2024-06-14 at 10 26 04 AM](https://github.com/18F/guides/assets/106776019/09533696-92a9-406d-9f5a-b811b350839d)

**Comment by adunkman** [comment]
Thanks Jason! I’m touching base with the revisions that are moving through content approvals right now to see if we’ll be continuing to reference these, or if they’re going to be removed anyways. I’ll loop back here shortly.

**Comment by adunkman** [comment]
Confirmed on a non-GSA device that the root issue is that the security certificate expired on January 14, 2024.

**Comment by adunkman** [comment]
We will continue to reference these in the revised content. Instead of linking to the sources, please only cite them. Since all three pages referenced already cite appropriately, feel free to remove the links and leave the content the same.

**Comment by cantsin** [comment]
@jasnakai I think we can close? I think the relevant PR was merged?

**Comment by jasnakai** [comment]
Done!
