### ISSUE TITLE
Publish new Archetypes method card

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/guides#566]
This is a follow-on issue to #289. 

Tasks: 
- [ ] Create new card for Methods section of the Guides.
- [ ] Create a pull request for the new card to be published (Reviewers: @MelissaBraxton @bpdesigns)
- [ ] Address any comments
- [ ] Merge changes

Acceptance criteria: 
- [ ] Archetypes method card is published

**Comment by bpdesigns** [comment]
@juliaklindpaintner merging this ticket with existing "Implementation ticket for #289
[#737](https://github.com/18F/TLC-crew/issues/737)"
