### ISSUE TITLE
Update the Methods card template

### ISSUE THREAD

**Issue by sam-couch-18f** [18F/guides#570]
### A description of the work

The existing [Methods card template](https://docs.google.com/document/d/1gBNvcB-Wtn0xqiM1-yEhhfcdE6ghcI6UXjWSGg7l3Do/edit) is out of date:
- "Example at 18F" section is not always relevant or included
- "Tips for remote participation" section is no longer used
- "Applied in government" section is now "Considerations for use in government"

### Point of contact on this issue

Ben or Sam

### Skills Needed

- [X] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [X] Yes
- [ ] No

### How much time do you anticipate this work taking?

< 1 hour

**Comment by bpdesigns** [comment]
@adunkman this is a straightforward task that came out of work @sam-couch-18f has been doing supporting guides tickets. @sam-couch-18f has the bandwidth in this sprint and is looking for work so I'll put this into prioritized. Please move if needed. Thanks.

**Comment by bpdesigns** [comment]
Yay!
