### ISSUE TITLE
[Request]: Add link to a11y guide from Heuristic Evaluation method card

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#610]
### A description of the work

This issue is a continuation of https://github.com/18F/guides/issues/400.

The Heuristic Evaluation method card would be a good place to surface the a11y guide's [checklist](https://guides.18f.gov/accessibility/checklist/). Add something like it under "Additional resources":

> Consider potential accessibility issues when evaluating the website using [18F's accessibility checklist](https://guides.18f.gov/accessibility/checklist/).

### Point of contact on this issue

@bpdesigns

### Skills Needed

- [ ] Any Human
- [ ] Design
- [X] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

Less than one day

### Acceptance Criteria

- [x] The [Heuristic Evaluation card](https://guides.18f.gov/methods/discover/heuristic-evaluation/) links to the [a11y guide's checklist page](https://guides.18f.gov/accessibility/checklist/)

**Comment by bpdesigns** [comment]
Implementation work from #400 that Mel started.
