### ISSUE TITLE
[Request]: Add a link to the research participant consent templates on the Recruiting method card

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#611]
### A description of the work

This issue is a continuation of https://github.com/18F/guides/issues/400.

We surface a link to the [Example design research participant agreement](https://guides.18f.gov/ux-guide/participant-agreement/)/[Ejemplo de acuerdo de participante de investigación de diseño](https://guides.18f.gov/ux-guide/participant-agreement-spanish/) on the Usability testing method card, but not the Recruiting card. It would be good to link to this from both.

### Point of contact on this issue

@bpdesigns

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

Less than one day

### Acceptance Criteria

- [ ] The [Recruiting method card](https://guides.18f.gov/methods/fundamentals/recruiting/) links to the [Spanish language version of the participant consent template](https://guides.18f.gov/ux-guide/participant-agreement-spanish/).
- [ ] The [Recruiting method card](https://guides.18f.gov/methods/fundamentals/recruiting/) links to the [English language version of the participant consent template](https://guides.18f.gov/ux-guide/participant-agreement/).

**Comment by bpdesigns** [comment]
Implementation work from #400 that Mel started.
