### ISSUE TITLE
[Request]: Add a link to the interview guide template on the Stakeholder and user interview method card

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#613]
### A description of the work

This issue is a continuation of https://github.com/18F/guides/issues/400.

We should add a link to the [Interview guide template](https://guides.18f.gov/ux-guide/usability-test-script/) on the [Stakeholder and user interview method card](https://guides.18f.gov/methods/discover/stakeholder-and-user-interviews/).

### Point of contact on this issue

@bpdesigns

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

Less than one day

### Acceptance Criteria

- [x] There is a link to the [Interview guide template](https://guides.18f.gov/ux-guide/usability-test-script/) on the [Stakeholder and user interview method card](https://guides.18f.gov/methods/discover/stakeholder-and-user-interviews/).

**Comment by bpdesigns** [comment]
Implementation work from #400 that Mel started.
