### ISSUE TITLE
[Request]: Add 10x acknowledgement to De-risking Guide About section in PDF

### ISSUE THREAD

**Issue by ameliaswong** [18F/guides#709]
### A description of the work

In the new De-risking Guide PDF About section, under "With thanks to," add as first bullet:

"GSA’s [10x program](https://10x.gsa.gov/investments/05-investments-in-tools-for-feds/) for enabling the De-risking Guide’s first launch, including evaluating and selecting the idea and providing phased funding from 2018 to 2020"

Person who elects to do this should know how to perform all necessary accessibility checks on the PDF.

### Point of contact on this issue

Amelia Wong

### Skills Needed

- [X] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [X] Yes
- [ ] No

### How much time do you anticipate this work taking?

1 hour

### Acceptance Criteria

The De-risking Guide PDF's About section includes acknowledgement of 10x as noted above, and the revised PDF has been published to guides.18f.gov/derisking-government-tech

**Comment by ameliaswong** [comment]
@melchoyce I don't expect you to pick this up, but thought you might appreciate FYSA. (And if you do pick it up, I'm sorry for the extra work since I know exporting the accessible PDF is tedious!)

**Comment by melchoyce** [comment]
I got it 👍 Do you think it's worth waiting a few days for any more corrections to shake out, or should I push out another PDF this week?

**Comment by ameliaswong** [comment]
Let's give it until next week since a lot of eyes are on it right now and may produce something.

**Comment by melchoyce** [comment]
I'm afk next week, but I can make fixes when I'm back on the 23rd!

**Comment by ameliaswong** [comment]
I think that's fine! That's a good span of time to have collected any other
corrections. Have fun at Wordcamp!

**Comment by melchoyce** [comment]
PDF has been updated: https://drive.google.com/file/d/1aCDVtm0YczpF-KCxEiomWV6BZYg83r9w/view?usp=drive_link

Assigning to @nateborr to upload to the site.

**Comment by nateborr** [comment]
The updated PDF is published on the site: https://guides.18f.gov/assets/derisking-government-tech/dist/18f-derisking-guide.pdf
