### ISSUE TITLE
[Request]: Write Derisking PDF export guide

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#729]
### A description of the work

I need to write up some documentation for how to export the PDF and process it so it's accessible.

**Comment by melchoyce** [comment]
I should include this:

https://youtu.be/hYC254yVYJM?si=9pYL5USeBuRKP8Ie&t=219

**Comment by edwintorres** [comment]
@melchoyce are you working on this? Should it be move to in progress?

**Comment by melchoyce** [comment]
Draft of this guide: https://docs.google.com/document/d/1GhXfMD7PLvUeqPtNm0Ex6fYZvu9fECbKaPek77Pst4Y/edit?usp=sharing

@igorkorenfeld could I have you gut check if you have the time?

**Comment by melchoyce** [comment]
Considering this done for now!
