### ISSUE TITLE
Protect the deployment process

### ISSUE THREAD

**Issue by beechnut** [18F/guides#755]
The approval and deployment process for the Guides seems a little too open.

**Reproduction steps:**

- Change content in the Engineering guide
- Submit the PR for approval
- Self-approve or have someone not in eng leadership approve the change

**Expected:**
- Merging / deploying should not be enabled
- A member of 18f/18f-eng-leadership should be required to approve before merging

**Actual:**
- Merging / deploying is enabled
- 18f/18f-eng-leadership is listed as a codeowner approver, but this doesn't block merging

**Comment by beechnut** [comment]
Pinging @adunkman (codeowner) for awareness. We should consider this for 18f.gsa.gov as well.

**Comment by adunkman** [comment]
This is a remnant of when we were doing guides migration — https://github.com/18F/guides/pull/65#issuecomment-1739413939. 

I agree, I will reconfigure this to require CODEOWNERS review and update here when complete.

**Comment by adunkman** [comment]
Updated to require code owner review — a screenshot from a recent pull request:

<img width="836" alt="image" src="https://github.com/user-attachments/assets/14220a4b-9124-4f2f-aa53-6b5dea1b153d">
