### ISSUE TITLE
Bug: fix styling for 404 page

### ISSUE THREAD

**Issue by echappen** [18F/guides#80]
The 404 page could use some design love, like a grid-container around the main content.

This may also entail finding a solution for fixing the footer to the bottom of the viewport when page content is really short.

Screenshot of current state:
 
![Screen Shot 2023-10-13 at 3 04 31 PM](https://github.com/18F/guides/assets/4267629/00cc5575-227b-491e-8e2e-5664b7e5bacd)

**Comment by alexbielen** [comment]
I'm going to update this to be a bugfix ticket and assign @igorkorenfeld . I'll make a new user story for the 404 page for @melchoyce
