### ISSUE TITLE
As a website visitor, when I navigate to a page that doesn't exist, I want to see a clear and user-friendly 404 error page so that I know the page is not available and I am able to easily navigate back to the main site

### ISSUE THREAD

**Issue by alexbielen** [18F/guides#84]
Acceptance Criteria: 

- [ ] When a visitor tries to access a page that does not exist (i.e., there is no URL mapping to resource) they should be redirected to the 404 error page.
- [ ] The 404 page has a message that indicates the page does not exist.
- [ ] The page is consistent with the Guides and Methods/18F Branding
- [ ] The page includes a link back to the website's home page.

**Comment by alexbielen** [comment]
@christophermather heads up that I created this user story for @melchoyce 's 404 page work.

**Comment by melchoyce** [comment]
One thing I'm realizing as I look through this: the guides don't share stylesheets and all have their own styles. For example, a11y using Helvetica Neue, but Agile uses Source Sans Pro:

| a11y | agile |
|--------|--------|
| ![image](https://github.com/18F/guides/assets/2846578/cd322bdf-a4e1-4f4e-a532-2fd38c8bb0cd) | ![image](https://github.com/18F/guides/assets/2846578/7cb85321-d11d-4a2a-82a3-622b9c2c6084) | 

The 18F website [has a 404 page we could use as a base](https://18f.gsa.gov/404/): 

![image](https://github.com/18F/guides/assets/2846578/f271c679-4bc1-4a0f-8f94-7c3a8aa96cdb)

But we wouldn't be able to universally apply it across all of the Guides sites.

Should I just ignore this and try to design one universal 404 page we can use, or is there a plan to eventually use the same centrally-designed template for all of the Guides sites?

**Comment by melchoyce** [comment]
Related: https://github.com/18F/guides/issues/80

**Comment by melchoyce** [comment]
Just went through all the Guides and Methods sites and they all currently have 404 pages. a11y, agile, derisking, methods, and product use the default Pages 404:

![image](https://github.com/18F/guides/assets/2846578/f39df006-a8c6-47a6-8d7d-00c8a80b5269)

Engineering, content, and ux use this:

![image](https://github.com/18F/guides/assets/2846578/60e2ca6f-1eb2-4db1-aaee-8754446edfc9)

**Comment by alexbielen** [comment]
Just checking -- are you looking at the existing guides or the replatformed guides?

**Comment by melchoyce** [comment]
The ones linked from https://18f.gsa.gov/guides/. How do I find the replatormed guides?

**Comment by alexbielen** [comment]
@igorkorenfeld or @eric-gade should be able to share the Cloud.gov Pages preview URL.

**Comment by eric-gade** [comment]
Hey @melchoyce! Right now only one replatformed guide is live -- the agile guide at https://guides.18f.gov/agile/
  
Unfortunately, per [this slack conversation](https://gsa-tts.slack.com/archives/C04823NMA/p1697746723212049), only the "live" site can use a custom 404 page. This means any off-main-branch Pages preview sites will not use a custom 404 page, even if it is present and configured correctly.
  
We have not yet merged the changes in that would show the replatformed site. I will let you know when we do so.

**Comment by eric-gade** [comment]
@melchoyce Ok the changes are merged and the agile site is up now. You can try [a link like this one](https://guides.18f.gov/agile/hello/) to get the custom 404 page that all of the new guides will eventually use.

**Comment by melchoyce** [comment]
Thanks!

**Comment by melchoyce** [comment]
## With side navigation

For Guides sites that make heavy use of the side navigation component (a11y, agile, content, ux).

![image](https://github.com/18F/guides/assets/2846578/54dc3b6c-fce5-47ef-a623-65231a471da9)

## Full-width

For Methods and the Guides sites which do not make heavy use of the side navigation component (de-risking, engineering). 

![image](https://github.com/18F/guides/assets/2846578/b4fe6fe2-1675-49b0-8d4e-43674b291510)

[You can find more details about the mockups on Figma.](https://www.figma.com/file/6WuJ9nxQvmkzxlUPoqTmJP/18F-Guides?type=design&node-id=0%3A1&mode=design&t=RI6i9s7K90hxIY3U-1). Whoever is implementing, let me know if you'd like to walk through it together, or have questions.

**Comment by melchoyce** [comment]
Belated thought: should we use https://designsystem.digital.gov/templates/404-page/?

**Comment by melchoyce** [comment]
If we wanted to use USWDS's 404 template:

![image](https://github.com/18F/guides/assets/2846578/c1a93f81-2200-448d-be60-ca2599391d9a)
[Figma](https://www.figma.com/file/6WuJ9nxQvmkzxlUPoqTmJP/18F-Guides-and-Methods?type=design&node-id=7-3325&mode=design&t=RI6i9s7K90hxIY3U-4)

**Comment by igorkorenfeld** [comment]
I believe that all of the guides will use a single 404 page, since it will apply to the whole site. That is, I don't think we can do a separate 404 with a particular guide's sidenav, unless we were able to capture which guide the user intended to go to.

**Comment by melchoyce** [comment]
Good to know, we'll want to use one of the full-width ones then. Do you think it's better to go simple or more comprehensive (the USWDS template) here @igorkorenfeld?

**Comment by igorkorenfeld** [comment]
Personally, I like the format of simple ones maybe with just a little more text like the 18F site has – specifically adding in the contact us link to 18F's contact page. The only other thought is that maybe it is worth adding "404" into the title since that is a commonly known and used error code?

**Comment by melchoyce** [comment]
Good ideas. How about something like this?

![image](https://github.com/18F/guides/assets/2846578/fd92c529-b0f3-4588-90e5-2ae5f0d3dd20)

**Comment by igorkorenfeld** [comment]
That looks great! Wondering how it is if it's left aligned with the logo instead of the center offset?

**Comment by melchoyce** [comment]
Ask and ye shall receive: 

![image](https://github.com/18F/guides/assets/2846578/0f02a1f7-84a0-472a-8bd1-e9f3ead4e5b8)

**Comment by igorkorenfeld** [comment]
I lean toward #2 but feel like both work. What do you think?

**Comment by melchoyce** [comment]
I don't think I have a preference, so let's go with the most recent iteration, with it left-aligned.

**Comment by eric-gade** [comment]
Slight aside: is there a particular reason the header for the 404 page says "18F Approaches"? Do we still want that?

**Comment by igorkorenfeld** [comment]
The header and nav components have a default option when the page is not a guide, and originally I set it up the header to be "Approaches" since that was the placeholder name. We can either set it to "Guides" or just blank?

**Comment by christophermather** [comment]
@igorkorenfeld I think the default option should be "Guides" for right now. I've made a separate ticket to track that change (#97 ).

As for adding an issue for implementing @melchoyce's 404 design - I can get this in later this afternoon (around 2:30pm ET).

**Comment by christophermather** [comment]
Question as I'm creating the implementation issue: "Visit homepage"... the intent here is to send users to the overall Guides homepage, correct? I'm assuming that's (far) easier than trying to map them to whichever guide they were intending to access.

**Comment by melchoyce** [comment]
If it's possible to get the intended guide I think that would be a better experience, but sending them to `18f.gsa.gov/guides/` is fine if not.

**Comment by eric-gade** [comment]
I can't think of a non-JS way to do it, given our level of server control.
  
If we were to do it with JS, the process would look something like:
1. User clicks the link, a JS event is captured (or fallback to main home page for non-JS enabled browsers)
2. We pull out the previous page from the browser history, and get it's URI
3. We trim the URI down to just the guide-name part, ie `guides.18f.gov/<guide-name>`
  
All of that can be done with a small script. But is it worth it?

**Comment by eric-gade** [comment]
Additionally, we can also make a link that just "goes back" to the previous page, similarly to what the back button would do

**Comment by melchoyce** [comment]
In some cases there might not be a back—for example, manually typing a URL, or pasting a link from somewhere else into your browser. I think we can just direct people to the Guides homepage.

**Comment by christophermather** [comment]
Keeping it real simple: let's go with sending them to `18f.gsa.gov/guides/` for now. I've made note of this in the implementation issue (#99 )

We can revisit more complex functionality in the future if it feels worth it.

**Comment by alexbielen** [comment]
@melchoyce @christophermather I believe this one is good to close now?

**Comment by melchoyce** [comment]
Yeah since there's a separate implementation issue, I think this is good to close!
