### ISSUE TITLE
Implement new 404 page design 

### ISSUE THREAD

**Issue by christophermather** [18F/guides#99]
From #84 , let's implement @melchoyce's new 404 design. A few notes:

- The page should inherit site defaults for header, nav, footer, etc.
- Per #97 , the header will actually be "Guides" rather than "Approaches
- We're implementing the left-aligned design (see below)
- "Contact us" should link to `https://18f.gsa.gov/contact/`
- "Visit homepage" should go to the overall Guides homepage (18f.gsa.gov/guides/)

![277807945-0f02a1f7-84a0-472a-8bd1-e9f3ead4e5b8](https://github.com/18F/guides/assets/97245800/7690e3a0-9c6c-43f3-8405-b8c2a7250af3)

Acceptance criteria:

- [ ] Any user trying to access a URL that can't be found on the Guides site encounters this redesigned 404 page

**Comment by melchoyce** [comment]
We do have a contact page on the 18F site: https://18f.gsa.gov/contact/

**Comment by christophermather** [comment]
Thanks, @melchoyce! Updated the issue with that link./
